from typing import Dict, Any, List, Optional
import io
import base64
import json
from datetime import datetime


class ReportGenerator:
    @staticmethod
    def generate_html(analysis_results: List[Dict[str, Any]], title: str = "StatLab AI Report") -> str:
        sections = ""
        for result in analysis_results:
            sections += f"""
            <div class="section">
                <h2>{result.get('test', result.get('analysis_type', 'Analysis'))}</h2>
                <div class="results">
            """
            for key, value in result.items():
                if key in ("interpretation",):
                    sections += f'<div class="interpretation"><strong>Interpretation:</strong> {value}</div>'
                elif key not in ("test", "analysis_type", "charts", "code_snippet", "matrix", "design_matrix"):
                    if isinstance(value, (int, float, str, bool)):
                        sections += f'<p><strong>{key.replace("_", " ").title()}:</strong> {value}</p>'
                    elif isinstance(value, list) and len(value) < 20:
                        sections += f'<p><strong>{key.replace("_", " ").title()}:</strong> {value}</p>'
            sections += """
                </div>
            </div>
            """

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{title}</title>
    <style>
        body {{ font-family: 'Inter', -apple-system, sans-serif; max-width: 900px; margin: 0 auto; padding: 40px 20px; color: #1a1a2e; background: #f8f9fa; }}
        .header {{ text-align: center; padding: 30px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; border-radius: 16px; margin-bottom: 30px; }}
        .header h1 {{ margin: 0; font-size: 2em; }}
        .header p {{ opacity: 0.9; }}
        .section {{ background: white; border-radius: 12px; padding: 24px; margin-bottom: 20px; box-shadow: 0 2px 8px rgba(0,0,0,0.06); }}
        .section h2 {{ color: #667eea; margin-top: 0; border-bottom: 2px solid #f0f0f0; padding-bottom: 12px; }}
        .results p {{ margin: 8px 0; }}
        .interpretation {{ background: #f0f4ff; padding: 16px; border-radius: 8px; margin: 16px 0; border-left: 4px solid #667eea; }}
        .footer {{ text-align: center; color: #888; font-size: 0.9em; margin-top: 40px; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>🚀 StatLab AI</h1>
        <p>Advanced Data Science & Statistical Toolkit</p>
        <p style="font-size:0.9em;">Report generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}</p>
    </div>
    {sections}
    <div class="footer">
        <p>Generated by StatLab AI — Built by Abhinay Sambherao</p>
        <p><a href="https://abhiinayy.in">https://abhiinayy.in</a></p>
    </div>
</body>
</html>"""

    @staticmethod
    def generate_pdf(html_content: str) -> bytes:
        try:
            from weasyprint import HTML
            pdf_bytes = HTML(string=html_content).write_pdf()
            return pdf_bytes
        except Exception as e:
            html_bytes = html_content.encode("utf-8")
            return html_bytes

    @staticmethod
    def generate_docx(analysis_results: List[Dict[str, Any]]) -> bytes:
        try:
            from docx import Document
            doc = Document()
            doc.add_heading("StatLab AI - Analysis Report", 0)
            doc.add_paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
            doc.add_paragraph("Built by Abhinay Sambherao | https://abhiinayy.in")
            doc.add_paragraph("")

            for result in analysis_results:
                doc.add_heading(result.get("test", result.get("analysis_type", "Analysis")), 1)
                table = doc.add_table(rows=1, cols=2)
                table.style = "Light Shading Accent 1"
                hdr = table.rows[0].cells
                hdr[0].text = "Metric"
                hdr[1].text = "Value"
                for key, value in result.items():
                    if key not in ("test", "analysis_type", "charts", "code_snippet", "interpretation", "matrix", "design_matrix"):
                        if isinstance(value, (int, float, str, bool)):
                            row_cells = table.add_row().cells
                            row_cells[0].text = key.replace("_", " ").title()
                            row_cells[1].text = str(value)
                if "interpretation" in result:
                    doc.add_paragraph("")
                    doc.add_heading("Interpretation", 2)
                    doc.add_paragraph(result["interpretation"])

            buf = io.BytesIO()
            doc.save(buf)
            return buf.getvalue()
        except Exception as e:
            return f"Report generation error: {e}".encode()

    @staticmethod
    def get_export_formats() -> List[str]:
        return ["html", "pdf", "docx"]
